Expose ARN for service so we don't have to manually construct it
cloudposse/terraform-aws-ecs-alb-service-task pull request #96
Opened 2021-02-02 17:11 UTC by X82Softworks

## what
* Expose ARN for service so we don't have to manually construct it

## why
* Ease of use and preventing user error

2021-02-02 21:29 UTC, nitrocode commented
/rebuild readme

2021-02-02 21:29 UTC, nitrocode commented
/rebuild-readme

2021-02-02 21:30 UTC, jamengual submitted a review, later dismissed

2021-02-02 21:30 UTC, nitrocode submitted a review, later dismissed

2021-02-02 21:31 UTC, nitrocode commented
/test all

2021-02-03 09:43 UTC, X82Softworks commented
Please let me know what changes I can make on this side to allow access and fix the 403s you're getting from your automated tools

2021-02-03 09:55 UTC, SweetOps commented
@X82Softworks take a look on error:

```sh
--- FAIL: TestExamplesComplete (19.82s)
442
    apply.go:15: 
443
        	Error Trace:	apply.go:15
444
        	            				examples_complete_test.go:26
445
        	Error:      	Received unexpected error:
446
        	            	FatalError{Underlying: error while running command: exit status 1; 
447
        	            	Error: Unsupported attribute
448
        	            	
449
        	            	  on ../../outputs.tf line 18, in output "service_arn":
450
        	            	  18:   value       = join("", aws_ecs_service.default.*.arn) != "" ? join("", aws_ecs_service.default.*.arn) : join("", aws_ecs_service.ignore_changes_task_definition.*.arn)
451
        	            	
452
        	            	This object does not have an attribute named "arn".
453
        	            	}
454
        	Test:       	TestExamplesComplete
455
FAIL
456
exit status 1
```

2021-02-03 15:02 UTC, SweetOps requested changes

2021-02-03 15:02 UTC, SweetOps commented on outputs.tf
> +  value       = join("", aws_ecs_service.default.*.arn) != "" ? join("", aws_ecs_service.default.*.arn) : join("", aws_ecs_service.ignore_changes_task_definition.*.arn)
```suggestion
  value       = join("", aws_ecs_service.default.*.id) != "" ? join("", aws_ecs_service.default.*.id) : join("", aws_ecs_service.ignore_changes_task_definition.*.id)
```

2021-02-03 15:27 UTC, SweetOps commented
/rebuild-readme

2021-02-03 15:38 UTC, SweetOps commented
@X82Softworks could you please allow upstream maintainers to make changes to your branch?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#:~:text=to%20your%20branch.-,Enabling%20repository%20maintainer%20permissions%20on%20existing%20pull%20requests,like%20to%20allow%20commits%20on.

2021-02-03 16:00 UTC, X82Softworks commented
@SweetOps There's no option available on my PR to allow that, do I need to have elevated permissions elsewhere to enable it?

2021-02-03 16:06 UTC, nitrocode commented
/test all

2021-02-04 14:05 UTC, SweetOps commented
@X82Softworks , I don't know... in my PRs that checkbox is present ...

run the following commands locally and commit:

```
make init
make readme
terraform fmt
```

2021-02-04 16:24 UTC, SweetOps commented
/test readme

2021-02-04 16:33 UTC, SweetOps commented
/test all

2021-02-04 17:12 UTC, SweetOps approved these changes

2021-02-04 17:12 UTC, merged